### ISSUE TITLE
Update optional dependency lsp installer

### ISSUE THREAD

**Issue by HallerPatrick** [HallerPatrick/py_lsp.nvim#10]
Due to deprecation use new lsp installer: https://github.com/williamboman/nvim-lsp-installer

**Comment by lixiao189** [comment]
Hello, why after installing this plugin, the neovim prompt that pyright-langserver couldn't be found.
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/44799572/162942057-3cef396e-6e1d-490a-bc41-1ab8d683e1e0.png">

PS: I use the [nvim-lsp-installer](https://github.com/williamboman/nvim-lsp-installer)

**Comment by lixiao189** [comment]
<img width="663" alt="image" src="https://user-images.githubusercontent.com/44799572/162942380-41ef577a-258e-4360-83f5-5cdb75aae7b9.png">
I just add setup like this, did I do something wrong?

**Comment by HallerPatrick** [comment]
Hey @lixiao189,

sorry for the late responds. The `host_python` is used for creating venvs inside of Neovim. And is not considered for a place for the language server. 

But you indeed right that the language server couldn't be found from this plugin, which I fixed now. So if `pyright` is installed with `nvim-lsp-installer` it now should work :)

**Comment by HallerPatrick** [comment]
stale
