### ISSUE TITLE
[Help]: more LSP support

### ISSUE THREAD

**Issue by younger-1** [HallerPatrick/py_lsp.nvim#12]
Currently the plugin supports `pyright` out of box. Is there any plannings of support other python LSP such as https://github.com/python-lsp/python-lsp-server and https://github.com/pappasam/jedi-language-server.

**Comment by HallerPatrick** [comment]
Hey! I looked into `Jedi` and managed to integrate it. Please look into a3fe2da704c0239c030db94d79ff4d9a03e51df8 how to use it.

Because I am not using any other lsp server besides `pyright` I would only support other LSPs, when explicitly asked for. Or someone PRs it :P

Greetings Patrick

**Comment by HallerPatrick** [comment]
#13
