### ISSUE TITLE
Issue with :PyFindVenvs

### ISSUE THREAD

**Issue by thomascrha** [HallerPatrick/py_lsp.nvim#20]
So when running this command I get this error 
![image](https://user-images.githubusercontent.com/5226462/209041242-372350aa-8d8b-47bb-afde-bb1f604b10e3.png)

Doing some research (and editing my `stratagies.lua` the function `table.unpack` isn't available in older versions of lua [info](https://github.com/Ben-Kerman/immersive/issues/6#issuecomment-812599401) - any way I was able to fix it by removing the `table.` 

Is this something you want to fix ? or should we recommend users update there Lua to 5.2 ?

**Comment by thomascrha** [comment]
PR with fix = https://github.com/HallerPatrick/py_lsp.nvim/pull/21

**Comment by HallerPatrick** [comment]
Sorry for the delayed response, but thanks for the contribution!
