### ISSUE TITLE
Automatic source from PyLspFindVenvs results

### ISSUE THREAD

**Issue by guilhermeprokisch** [HallerPatrick/py_lsp.nvim#27]
There's an option to automatically source from PyLspFindVenvs results? I mean, I always have a .venv on my project root so there's any way to pass the PyLspFindVenvs results automatically activation?

**Comment by HallerPatrick** [comment]
Hey! 

I am not quite sure about sourcing all  results from PyLspFindVenvs. But if you always have a .venv in your project root you can set `default_venv_name`.


Like:
```
require("py_lsp").setup({
   -- Look for virtual environment with name ".venv" 
    default_venv_name = ".venv"
})
```

Hope this helps with your problem :)
