### ISSUE TITLE
misspelled: nvim-lua/completion-nvim

### ISSUE THREAD

**Issue by vlcinsky** [HallerPatrick/py_lsp.nvim#3]
README is using plugin name `nvim-lua/completion.nvim`.

It effectively prevents installing this plugin.

It shall read `nvim-lua/completion-nvim`

**Comment by smjonas** [comment]
You're right, I messed that up in my PR. I even had it correct in my own config, oh well :)

**Comment by HallerPatrick** [comment]
Thanks for this detail @vlcinsky . This is now resolved :)
