### ISSUE TITLE
Make FindLspFindVenvs showing a short env name at head?

### ISSUE THREAD

**Issue by puppyapple** [HallerPatrick/py_lsp.nvim#31]
<img width="695" alt="image" src="https://user-images.githubusercontent.com/33118185/227125179-515184ee-b5cf-45b3-9e28-65f5a2e453cf.png">
For now, the FindLspFindVenvs show the usable env python path like this, but in fact it is hard to find the wanted one in absolute path. So perhaps it will be better to have the env name at the beginning? Some thing like【(Conda: py38) /home/xx/anaconda3/envs/py38/bin/python】.
Thanks for the great work by the way.

**Comment by HallerPatrick** [comment]
Thanks for the feedback!

With the help of `fzf` finding the target venv should be easy. But looking for the target venv, where you forgot the name, might take some time. It also would probably look a little bit more pleasing with a venv prefix.

**Comment by puppyapple** [comment]
> Thanks for the feedback!
> 
> With the help of `fzf` finding the target venv should be easy. But looking for the target venv, where you forgot the name, might take some time. It also would probably look a little bit more pleasing with a venv prefix.

Yeah, with telescope we could also type a few key word to filter.
