### ISSUE TITLE
Error message about notify

### ISSUE THREAD

**Issue by spring-haru** [HallerPatrick/py_lsp.nvim#41]
macOS 14.6.1
neovim 0.10.2

I use conda and nvim-lspconfig, and added

```
require 'py_lsp'.setup {
  host_python = "~/opt/anaconda3/envs/py12/bin",
  default_venv_name = ".venv"
}
``` 
in `init.lua`, as explained. `:checkhealth` shows that `py_lsp` correctly sets the above environment. However, if a `.py` file is opened, the following message is shown:

```
LSP[pyright]: Error ON_INIT_CALLBACK_ERROR: "...l/share/nvim-quarto/lazy/py_lsp.nvim/lua/py_lsp/init.lua:28: attempt to call field 'notify' (a nil value)"
```

Can you help to sort this out?

**Comment by HallerPatrick** [comment]
Hello @spring-haru,

thanks for the bug report! This is indeed a bug. I fixed it. It should not throw an error message now. 

Best regards
